baseURL = ""
languageCode = "en-ca"
title = "Alex Koen"
timeout = 60000

[author]
  name = "Alex Koen"

[params]
  description = "Engineering student, writer, climber and photographer."
  pluralizeListTitles = false
  landscapePhotoWidths = [2500, 1500, 1000]
  portraitPhotoWidths = [1500, 1000, 750]
  thumbQuality = "400x400 q75 Center"

[imaging.exif]
  includeFields = ".*"

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[_build]
  publishResources = false