baseURL = ""
languageCode = "en-ca"
title = "Alex Koen"
timeout = 300000

[author]
  name = "Alex Koen"

[params]
  description = "Engineering student, writer, climber and photographer."
  pluralizeListTitles = false

  imageThumbQuality = "x400 q75"
  imageResponsiveWidths = [2400, 1600, 1200, 800, 400]

[imaging.exif]
  includeFields = ".*"

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[_build]
  publishResources = false