baseURL = ""
languageCode = "en-ca"
title = "Alex Koen"
timeout = 300000

[author]
  name = "Alex Koen"

[params]
  description = "Engineering student, writer, climber and photographer."
  pluralizeListTitles = false

  imageThumbQuality = "x400 q75"
  imageResponsiveWidths = [1500, 1000, 800, 400]
  imageWidths = "(min-width: 35em) 1200px, 100vw"

[imaging.exif]
  includeFields = ".*"

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[_build]
  publishResources = false