baseURL = ""
languageCode = "en-ca"
title = "Alex Koen"

[params]
	author = "Alex Koen"
  landscapePhotoWidths = [2500, 1500, 1000]
  portraitPhotoWidths = [1500, 1000, 750]
  pluralizeListTitles = false

[imaging.exif]
  includeFields = ".*"

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[_build]
  publishResources = false