baseURL = ""
languageCode = "en-ca"
title = "Alex Koen"
timeout = 60000

[author]
  name = "Alex Koen"

[params]
  description = "Engineering student, writer, climber and photographer."
  pluralizeListTitles = false

  imageThumbQuality = "400x400 q75 Center"
  imageResponsiveWidths = [2500, 1500, 1000]
  imageWidths = "(min-width: 35em) 1200px, 100vw"

[imaging.exif]
  includeFields = ".*"

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[_build]
  publishResources = false