[build]
    # Directory in which to build
    base = "docs/"

    # Directory to publish from
    publish = "docs/"

[[redirects]]
    # Redirect all blog queries to subdomain
    from = "/writing/*"
    to = "https://blog.alexkoen.com/:splat"
    status = 200