#+Title: Cast Iron Lily Outline

*Synopsis:* This year I co-wrote an original play with five of my classmates. I have no intention of pursuing acting as a career, but it is the most valuable experience I have ever had

*Article:*

Disclaimer: This article is under constant revision as I try to qualify the complex feeling I have about this play.

I don't know who you are, where you live, or what you do in your free time. What I do know, however, is what you want: you want to feel accepted. I know this because we all do—it is a collective experience of humanity to yearn for human connection and to desire, more than anything, to be heard and understood. Nowadays, however, this yearning for community that we so desire so greatly is being left unsatiated as we are becoming more and more isolated.

In Grade 10, I made the somewhat spontaneous decision of enrolling in my school's theatre program. While I knew that I enjoyed drama and that it would provide a much-needed distraction from my academic courses, what I didn't know was the extent to which the program would change my life and alter the way I see the world forever.

Every year, the Handsworth Secondary theatre program performs an original play written by Grade 12 students and performed by members of the school's art departments. This is not only unrivalled in its ambition—the show regularly exceeds $50,000 in ticket sales—but also in it's scale: this year's cast was comprised of over 200 actors, singers, dancers, and technicians. As one of six head writers for this year's show, /Cast Iron Lily/ I was intimately involved with the entire process, from brainstorming concept ideas to making last-minute changes. We spent weeks deliberating over various ideas for the show, from a Broadway-inspired Alien vs Predator musical, to a film-noir style crime thriller set in 1920's America. What we eventually settled upon, however, was something far more impactful—we wrote a play about the Me Too movement.

As someone who is fortunate enough not to have experienced sexual assault, I am not qualified to 

This decision proved to be somewhat contentious. I, like many of those who have been fortunate enough not to have experienced sexual assault, felt that, while important, the movement wasn't universal enough to base a play around.


While our play did center around sexual assault and reconciliation, the underlying theme was of something even more pervasive in today's society: the need for support. Since 2006, thousands of women and men have come out against high-profile sexual assault in the workplace, yet the problem is far larger. The reality is that most people do not have anyone whom they trust enough to rely upon during these difficult times. Cast Iron Lily focused on this need for support, with its plot following the exploitation of women in a World War II munitions factory and its parallels in the 21st century. We wanted to send the message to everyone who has stories that they have yet to tell that we will listen, and that we will be there for them if they decide they are ready. 

* Extra 

In a recent study on loneliness, nearly half of the participants reported often feeling lonely or left out, with young adults aged 18–22 reporting the highest levels of social isolation of all. As an 18-year old graduating from high-school, this fact could not be more apparent to me. People don't connect anymore. We live our lives isolated from each other, not physically, but emotionally, as we are taught to repress our feelings out of fear.
